# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicators', '0001_initial'),
        ('read', '0002_auto_20150202_1342'),
        ('silo', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitativeoutputs',
            name='logframe_indicator',
            field=models.ForeignKey(blank=True, to='indicators.Indicator', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='province',
            name='country',
            field=models.ForeignKey(to='activitydb.Country'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='approval_submitted_by',
            field=models.ForeignKey(related_name='requesting', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='approved_by',
            field=models.ForeignKey(related_name='approving', blank=True, to=settings.AUTH_USER_MODEL, help_text=b'This is the Provincial Line Manager', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='community',
            field=models.ManyToManyField(to='activitydb.Community', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='estimated_by',
            field=models.ForeignKey(related_name='estimate', blank=True, to=settings.AUTH_USER_MODEL, help_text=b'This is the originator', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='office',
            field=models.ForeignKey(blank=True, to='activitydb.Office', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='program',
            field=models.ForeignKey(related_name='proposal', blank=True, to='activitydb.Program', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='project_type',
            field=models.ForeignKey(blank=True, to='activitydb.ProjectType', max_length=255, help_text=b'Please refer to Form 05 - Project Progress Summary', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='sector',
            field=models.ForeignKey(blank=True, to='activitydb.Sector', max_length=255, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectcomplete',
            name='approval_submitted_by',
            field=models.ForeignKey(related_name='submitted_by_complete', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectcomplete',
            name='approved_by',
            field=models.ForeignKey(related_name='approving_agreement_complete', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectcomplete',
            name='checked_by',
            field=models.ForeignKey(related_name='checking_complete', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectcomplete',
            name='community',
            field=models.ManyToManyField(to='activitydb.Community', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectcomplete',
            name='estimated_by',
            field=models.ForeignKey(related_name='estimating_complete', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectcomplete',
            name='office',
            field=models.ForeignKey(blank=True, to='activitydb.Office', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectcomplete',
            name='program',
            field=models.ForeignKey(related_name='complete', blank=True, to='activitydb.Program', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectcomplete',
            name='project_agreement',
            field=models.ForeignKey(to='activitydb.ProjectAgreement'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectcomplete',
            name='project_proposal',
            field=models.ForeignKey(to='activitydb.ProjectProposal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectcomplete',
            name='reviewed_by',
            field=models.ForeignKey(related_name='reviewing_complete', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='approval_submitted_by',
            field=models.ForeignKey(related_name='submitted_by_agreement', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='approved_by',
            field=models.ForeignKey(related_name='approving_agreement', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='checked_by',
            field=models.ForeignKey(related_name='checking', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='community',
            field=models.ManyToManyField(to='activitydb.Community', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='estimated_by',
            field=models.ForeignKey(related_name='estimating', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='finance_reviewed_by',
            field=models.ForeignKey(related_name='finance_reviewing', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='me_reviewed_by',
            field=models.ForeignKey(related_name='reviewing_me', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='office',
            field=models.ForeignKey(blank=True, to='activitydb.Office', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='program',
            field=models.ForeignKey(related_name='agreement', blank=True, to='activitydb.Program', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='project_proposal',
            field=models.ForeignKey(to='activitydb.ProjectProposal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='project_type',
            field=models.ForeignKey(blank=True, to='activitydb.ProjectType', max_length=255, help_text=b'Please refer to Form 05 - Project Progress Summary', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='reviewed_by',
            field=models.ForeignKey(related_name='reviewing', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='sector',
            field=models.ForeignKey(blank=True, to='activitydb.Sector', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='programdashboard',
            name='program',
            field=models.ForeignKey(blank=True, to='activitydb.Program', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='programdashboard',
            name='project_agreement',
            field=models.ForeignKey(blank=True, to='activitydb.ProjectAgreement', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='programdashboard',
            name='project_completion',
            field=models.ForeignKey(blank=True, to='activitydb.ProjectComplete', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='programdashboard',
            name='project_proposal',
            field=models.ForeignKey(blank=True, to='activitydb.ProjectProposal', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='program',
            name='country',
            field=models.ManyToManyField(to='activitydb.Country'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='office',
            name='province',
            field=models.ForeignKey(to='activitydb.Province'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='monitor',
            name='agreement',
            field=models.ForeignKey(blank=True, to='activitydb.ProjectAgreement', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='monitor',
            name='complete',
            field=models.ForeignKey(blank=True, to='activitydb.ProjectComplete', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mergemap',
            name='project_agreement',
            field=models.ForeignKey(to='activitydb.ProjectAgreement', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mergemap',
            name='project_completion',
            field=models.ForeignKey(to='activitydb.ProjectComplete', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mergemap',
            name='project_proposal',
            field=models.ForeignKey(to='activitydb.ProjectProposal', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mergemap',
            name='read',
            field=models.ForeignKey(to='read.Read'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='documentation',
            name='project',
            field=models.ForeignKey(blank=True, to='activitydb.ProjectProposal', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='documentation',
            name='silo',
            field=models.ForeignKey(blank=True, to='silo.Silo', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='documentation',
            name='template',
            field=models.ForeignKey(blank=True, to='activitydb.Template', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(to='activitydb.Province'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='contribution',
            name='project_agreement',
            field=models.ForeignKey(related_name='c_agreement', blank=True, to='activitydb.ProjectAgreement', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='contribution',
            name='project_complete',
            field=models.ForeignKey(related_name='c_complete', blank=True, to='activitydb.ProjectComplete', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='community',
            name='approved_by',
            field=models.ForeignKey(related_name='comm_approving', blank=True, to=settings.AUTH_USER_MODEL, help_text=b'This is the Provincial Line Manager', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='community',
            name='country',
            field=models.ForeignKey(to='activitydb.Country'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='community',
            name='district',
            field=models.ForeignKey(blank=True, to='activitydb.District', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='community',
            name='filled_by',
            field=models.ForeignKey(related_name='comm_estimate', blank=True, to=settings.AUTH_USER_MODEL, help_text=b'This is the originator', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='community',
            name='office',
            field=models.ForeignKey(default=b'1', to='activitydb.Office'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='community',
            name='province',
            field=models.ForeignKey(blank=True, to='activitydb.Province', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='community',
            name='village',
            field=models.ForeignKey(blank=True, to='activitydb.Village', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='budget',
            name='agreement',
            field=models.ForeignKey(blank=True, to='activitydb.ProjectAgreement', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='community',
            field=models.ForeignKey(blank=True, to='activitydb.Community', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='training',
            field=models.ForeignKey(blank=True, to='activitydb.TrainingAttendance', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='benchmarks',
            name='agreement',
            field=models.ForeignKey(blank=True, to='activitydb.ProjectAgreement', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='benchmarks',
            name='complete',
            field=models.ForeignKey(blank=True, to='activitydb.ProjectComplete', null=True),
            preserve_default=True,
        ),
    ]
